### ISSUE TITLE
editUser  rest API shows error while updating

### ISSUE THREAD

**Issue by veluvj** [bharathmit/audit-ui#1]
while trying to update users detail from reactive form it shows an error

The response  given by the postman interceptor
```
timestamp": "2019-12-05T08:42:42.465+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Unable to find com.audit.app.entity.UserRole with id 2; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.audit.app.entity.UserRole with id 2",
    "path": "/user"
```
The response given by the Swagger UI
```
{
  "status": "BAD_REQUEST",
  "timestamp": "05-12-2019 08:32:44",
  "error": "Business Exception",
  "message": "Email Id Already Exit",
  "path": "/user",
  "traceId": "NoopSpan(680b5c15ca317c2b/680b5c15ca317c2b)",
  "subErrors": null
}
```

Object that i had given to update the user details

```
  {
      "userId": 2,
        "firstName": "manivel",
        "middleName": null,
        "lastName": null,
        "otherName": null,
        "mobile": "83300855041",
        "phoneNumber": null,
        "emailId": "veluvijay1804@gmail.com",
        "dob": null,
        "gender": "Male",
        "maritalStatus": "Single",
        "gstpNumber": "12345",
        "address": "Tamilnadu,India",
        "pinCode": "639004",
        "qulification": null,
        "status": "InActive",
        "userRoles": [
            {
                "userRoleId": 2,
                "role": {
                    "roleId": 1,
                    "roleName": "User",
                    "status": "Active"
                },
                "status": "Active"
            }
        ],
        "lastLoginDate": null,
        "passwordChangeDate": null,
        "lockDate": null,
        "photo": null
    }
```

I had updated the above details but it shows an error

**Comment by bharathmit** [comment]
Try this,


{
      "userId": 2,
        "firstName": "manivel",
        "middleName": null,
        "lastName": null,
        "otherName": null,
        "mobile": "83300855041",
        "phoneNumber": null,
        "emailId": "veluvijay1804@gmail.com",
        "dob": null,
        "gender": "Male",
        "maritalStatus": "Single",
        "gstpNumber": "12345",
        "address": "Tamilnadu,India",
        "pinCode": "639004",
        "qulification": null,
        "status": "InActive",
        "userRoles": [
            {
                "role": {
                    "roleId": 1,
                    "roleName": "User",
                    "status": "Active"
                },
                "status": "Active"
            }
        ],
        "lastLoginDate": null,
        "passwordChangeDate": null,
        "lockDate": null,
        "photo": null
    }


Updating user details you no need to pass "userRoleId": 2, this field


Regards,
Bharath

**Comment by bharathmit** [comment]
Backend have to remove the id
